const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Orbit,
		C3.Behaviors.Sin,
		C3.Behaviors.NoSave,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Text.Exps.Height
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Piscar: 0},
	{Personagem: 0},
	{Teclado: 0},
	{Sólido: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{PlanoDeFundoEmBlocos: 0},
	{portal: 0},
	{Sprite8: 0},
	{Sprite11: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite13: 0},
	{lava1: 0},
	{lava2: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Vulcao2: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite12: 0},
	{Sprite14: 0},
	{Órbita: 0},
	{portalAzul: 0},
	{Senóide: 0},
	{portalRosa: 0},
	{plataformaAmarela: 0},
	{NãoSalvar: 0},
	{plataformaVerde: 0},
	{plataformaAmarela2: 0},
	{plataformaVermelho: 0},
	{plataformaVermelhosolid: 0},
	{portalfinal: 0},
	{Âncora: 0},
	{Texto: 0},
	{Sprite7: 0},
	{Senóide2: 0},
	{personagemmenu: 0},
	{creditosmenu: 0},
	{botaojogar: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{menufinal: 0},
	{Sprite29: 0},
	{botaoMute: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Mouse: 0},
	{Sprite16: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{voltarcredito: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite10: 0},
	{Sprite15: 0},
	{jogarpause: 0},
	{Sprite30: 0},
	{Sprite32: 0},
	{Sprite42: 0},
	{Sprite44: 0},
	{botaosair: 0},
	{Áudio: 0},
	{Sprite9: 0},
	{Sprite27: 0},
	{Pause_Status: 0},
	{estado: 0},
	{Tempo: 0},
	{iniciojogo: 0},
	{pause: 0},
	{mute: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Personagem: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	portal: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	lava1: class extends self.ISpriteInstance {},
	lava2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Vulcao2: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	portalAzul: class extends self.ISpriteInstance {},
	portalRosa: class extends self.ISpriteInstance {},
	plataformaAmarela: class extends self.ISpriteInstance {},
	plataformaVerde: class extends self.ISpriteInstance {},
	plataformaAmarela2: class extends self.ISpriteInstance {},
	plataformaVermelho: class extends self.ISpriteInstance {},
	plataformaVermelhosolid: class extends self.ISpriteInstance {},
	portalfinal: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	personagemmenu: class extends self.ISpriteInstance {},
	creditosmenu: class extends self.ISpriteInstance {},
	botaojogar: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	menufinal: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	botaoMute: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	voltarcredito: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	jogarpause: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	botaosair: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Pause_Status: class extends self.ITextInstance {}
}